language: python
sudo: false

cache:
 directories:
  - $HOME/virtualenv
  - $HOME/miniconda

env:
  global:
  - CACHE_DIR="$HOME/virtualenv"
  - MINICONDA_DIR="$HOME/miniconda"
  - PYTHONIOENCODING=UTF8

python:
  - 2.7
  - 3.4
  - 3.5

git:
  depth: 3

before_install:
  - travis/before_install.sh

install:
  - travis/install-conda.sh
  - export PATH="$PATH:$HOME/miniconda/bin"
  - hash -r
  - travis/install-pip.sh
  - travis/install-tools.sh

script:
  - travis/tests-unit.sh
  - travis/tests-long.sh

after_success:
  - coveralls
