name: cms-env
channels:
- bioconda
- defaults
dependencies:
- alabaster=0.7.8=py35_0
- babel=2.3.3=py35_0
- bcftools=1.3.1=0
- boltons=16.4.1=py35_0
- curl=7.45.0=1
- htslib=1.3.1=0
- peewee=2.8.0=py35_1
- pysam=0.9.1=py35_0
- python-dateutil=2.3=py35_0
- samtools=1.3.1=1
- selscan=1.1.0b=0
- biopython=1.67=np111py35_0
- cloog=0.18.0=0
- docutils=0.12=py35_2
- ecdsa=0.13=py35_0
- gcc=4.8.5=3
- gmp=5.1.2
- imagesize=0.7.1=py35_0
- isl=0.12.2
- jinja2=2.8=py35_1
- libgcc=4.8.5=1
- markupsafe=0.23=py35_2
- mkl=11.3.3=0
- mpc=1.0.1=0
- mpfr=3.1.2=0
- ncurses=5.9=0
- numpy=1.11.0=py35_1
- openssl=1.0.2h=1
- pandas=0.18.1=np111py35_0
- paramiko=1.16.0=py35_0
- pip=8.1.2=py35_0
- pycrypto=2.6.1=py35_4
- pygments=2.1.3=py35_0
- python=3.5.1=0
- pytz=2016.4=py35_0
- readline=6.2=2
- setuptools=23.0.0=py35_0
- six=1.10.0=py35_0
- snowballstemmer=1.2.1=py35_0
- sphinx_rtd_theme=0.1.9=py35_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- zlib=1.2.8=3
- pip:
  - apipkg==1.4
  - boltons==16.4.1
  - coverage==4.1
  - coveralls==1.1
  - docopt==0.6.2
  - execnet==1.4.1
  - flake8==2.6.0
  - mccabe==0.5.0
  - mock==2.0.0
  - pbr==1.10.0
  - peewee==2.8.0
  - py==1.4.31
  - pycodestyle==2.0.0
  - pyflakes==1.2.3
  - pysam==0.9.1
  - pytest==2.9.2
  - pytest-cov==2.2.1
  - pytest-xdist==1.14
  - python-dateutil==2.3
  - requests==2.10.0
  - sphinx==1.4.4
  - sphinx-argparse==0.1.15
  - sphinx-rtd-theme==0.1.9

